fixtures:
  symlinks:
    bluepill: "#{source_dir}"
  repositories:
    logrotate: "git://github.com/rodjek/puppet-logrotate"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    r9util: "git://github.com/kayakco/puppet-r9util"
